server:
  port: 8085

spring:
  application:
    name: reactive-bff

logging:
  level:
    com.estudo: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 200
        readTimeout: 5000
        loggerLevel: full
        defaultRequestHeaders:
          User-Agent: ${spring.application.name}
          Accept: "application/json"
        decode404: true