credit-card:
  url: http://localhost:8000
  tracking: http://localhost:8000

resilience4j:
  circuitbreaker:
    instances:
      creditCard:
        baseConfig: default
      tracking:
        baseConfig: default
  retry:
    instances:
      creditCard:
        baseConfig: default
      tracking:
        baseConfig: default